Revert "Adding entry-point based support for out-of-tree rendezvous plugins (#132633)"
This reverts commit 09aff99fdb6d65ff156c4236c7777c067312a1e4.

Reverted https://github.com/pytorch/pytorch/pull/132633 on behalf of https://github.com/ZainRizvi due to Sorry but this is causing internal tests to fail with the error `ImportError: cannot import name '_register_out_of_tree_handlers' from 'torch.distributed.elastic.rendezvous.registry'` ([comment](https://github.com/pytorch/pytorch/pull/132633#issuecomment-2315716201))