Revert "[user errors] compulsory case names, allow multiple (#110878)"
This reverts commit 4b188751d43d23c3ce028dae28a4d69bc09e1708.

Reverted https://github.com/pytorch/pytorch/pull/110878 on behalf of https://github.com/kit1980 due to export/test_export.py::TestExport::test_multiple_definitions_same_name_dim - TypeError: UserError.init() missing 1 required positional argument: 'case_names' ([comment](https://github.com/pytorch/pytorch/pull/110878#issuecomment-1754360051))