Revert "Support masked_fill (#88736)"
This reverts commit 983ef727ce353f66c84223c7abbaf745db66d8ba.

Reverted https://github.com/pytorch/pytorch/pull/88736 on behalf of https://github.com/kit1980 due to Inductor tests are failing with AttributeError: module 'torch._inductor.codecache' has no attribute 'valid_vec_isa_list'