Revert "export AOTI_TORCH_EXPORT on Windows. (#140030)"
This reverts commit 76f96534b9648cc55f9404ff9131fbb9879c5ba4.

Reverted https://github.com/pytorch/pytorch/pull/140030 on behalf of https://github.com/atalman due to Break internal tests see errors like: csrc\inductor\aoti_torch\shim_common.cpp(481): error C2491: 'aoti_torch__embedding_bag': definition of dllimport function not allowed ([comment](https://github.com/pytorch/pytorch/pull/140030#issuecomment-2523968128))