Revert "Remove Caffe2 python code (#126035)"
This reverts commit 706368c457f804d4a20dae8bfe34577fa78157fc.

Reverted https://github.com/pytorch/pytorch/pull/126035 on behalf of https://github.com/jeanschmidt due to Seems to have introduced lint error: Error: Module 'onnx' has no attribute 'numpy_helper' ([comment](https://github.com/pytorch/pytorch/pull/126035#issuecomment-2110570863))